# %%
# Compiles only files and place them in the ./output/for_paper/ directory (not gitignored)

# %%
import re
from tqdm import tqdm
import time
import os
from dotenv import load_dotenv
import ast
import shutil

time_start = time.time()

# %%
# 0 --- Main settings
load_dotenv()
path_output = "./output/"
path_for_paper = "./charts_for_papers/"

# %%
# I --- Function


def copy_files(input_path, input_file_names, output_path):
    # Loop through each file in the list
    for input_file_name in input_file_names:
        # Check if the file exists
        if os.path.isfile(input_path + input_file_name):
            # Copy the file to the destination directory
            shutil.copy(input_path + input_file_name, output_path)
            print(f"Copied {input_path + input_file_name} to {output_path}")
        else:
            print(f"File not found: {input_path + input_file_name}")


# %%
# II --- Compile selected files (can instead softcode, but hardcoding makes it easier to define specific set)
selected_file_names = [
    "stacked_area_lineplot_globaldebt",
    "lineplot_gepu",
    "scatter_regime_ratesinlevels_hhdebt_ngdp_gdp_against_maxminepu",
    "scatter_regime_ratesinlevels_govdebt_ngdp_gdp_against_maxminepu",
    "scatter_regime_ratesinlevels_hhdebt_ngdp_corecpi_against_maxminepu",
    "scatter_regime_ratesinlevels_govdebt_ngdp_corecpi_against_maxminepu",
    "scatter_regime_ratesinlevels_hhdebt_ngdp_cpi_against_maxminepu",
    "scatter_regime_ratesinlevels_govdebt_ngdp_cpi_against_maxminepu",
    "lineplot_hhdebt_ngdp_ref",
    "lineplot_corpdebt_ngdp_ref",
    "lineplot_govdebt_ngdp_ref",
    "lineplot_hhdebt",
    "lineplot_corpdebt",
    "lineplot_govdebt",
    "lineplot_maxminepu",
    "lineplot_maxminstir",
    "lineplot_ratesinlevels_epu",
    "lineplot_ratesinlevels_stir",
    "output/thresholdselection_aicc_contour.png",
    "quadrant_panelthresholdlp_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminstir_shockmaxminepu",
    "quadrant_panelthresholdlp_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminstir_shockmaxminepu_responsegdp",
    "quadrant_panelthresholdlp_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminstir_shockmaxminepu_responsecorecpi",
    "quadrant_panelthresholdlp_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminstir_shockmaxminepu",
    "quadrant_panelthresholdlp_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminstir_shockmaxminepu_responsegdp",
    "quadrant_panelthresholdlp_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminstir_shockmaxminepu_responsecorecpi",
    "quadrant_panelthresholdlp_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminstir_shockmaxminstir",
    "quadrant_panelthresholdlp_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminstir_shockmaxminstir_responsegdp",
    "quadrant_panelthresholdlp_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminstir_shockmaxminstir_responsecorecpi",
    "quadrant_panelthresholdlp_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminstir_shockmaxminstir",
    "quadrant_panelthresholdlp_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminstir_shockmaxminstir_responsegdp",
    "quadrant_panelthresholdlp_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminstir_shockmaxminstir_responsecorecpi",
    "quadrant_panelthresholdlp_reduced_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminstir_shockmaxminepu",
    "quadrant_panelthresholdlp_reduced_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminstir_shockmaxminepu_responsegdp",
    "quadrant_panelthresholdlp_reduced_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminstir_shockmaxminepu_responsecorecpi",
    "quadrant_panelthresholdlp_reduced_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminstir_shockmaxminepu",
    "quadrant_panelthresholdlp_reduced_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminstir_shockmaxminepu_responsegdp",
    "quadrant_panelthresholdlp_reduced_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminstir_shockmaxminepu_responsecorecpi",
    "quadrant_panelthresholdlp_reduced_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminstir_shockmaxminstir",
    "quadrant_panelthresholdlp_reduced_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminstir_shockmaxminstir_responsegdp",
    "quadrant_panelthresholdlp_reduced_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminstir_shockmaxminstir_responsecorecpi",
    "quadrant_panelthresholdlp_reduced_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminstir_shockmaxminstir",
    "quadrant_panelthresholdlp_reduced_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminstir_shockmaxminstir_responsegdp",
    "quadrant_panelthresholdlp_reduced_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminstir_shockmaxminstir_responsecorecpi",
    "quadrant_panelthresholdlp_ltir_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminltir_shockmaxminepu",
    "quadrant_panelthresholdlp_ltir_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminltir_shockmaxminepu_responsegdp",
    "quadrant_panelthresholdlp_ltir_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminltir_shockmaxminepu_responsecorecpi",
    "quadrant_panelthresholdlp_ltir_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminltir_shockmaxminepu",
    "quadrant_panelthresholdlp_ltir_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminltir_shockmaxminepu_responsegdp",
    "quadrant_panelthresholdlp_ltir_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminltir_shockmaxminepu_responsecorecpi",
    "quadrant_panelthresholdlp_ltir_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminltir_shockmaxminltir",
    "quadrant_panelthresholdlp_ltir_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminltir_shockmaxminltir_responsegdp",
    "quadrant_panelthresholdlp_ltir_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminltir_shockmaxminltir_responsecorecpi",
    "quadrant_panelthresholdlp_ltir_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminltir_shockmaxminltir",
    "quadrant_panelthresholdlp_ltir_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminltir_shockmaxminltir_responsegdp",
    "quadrant_panelthresholdlp_ltir_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminltir_shockmaxminltir_responsecorecpi",
    "quadrant_panelthresholdlp_ltir_reduced_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminltir_shockmaxminepu",
    "quadrant_panelthresholdlp_ltir_reduced_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminltir_shockmaxminepu_responsegdp",
    "quadrant_panelthresholdlp_ltir_reduced_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminltir_shockmaxminepu_responsecorecpi",
    "quadrant_panelthresholdlp_ltir_reduced_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminltir_shockmaxminepu",
    "quadrant_panelthresholdlp_ltir_reduced_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminltir_shockmaxminepu_responsegdp",
    "quadrant_panelthresholdlp_ltir_reduced_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminltir_shockmaxminepu_responsecorecpi",
    "quadrant_panelthresholdlp_ltir_reduced_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminltir_shockmaxminltir",
    "quadrant_panelthresholdlp_ltir_reduced_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminltir_shockmaxminltir_responsegdp",
    "quadrant_panelthresholdlp_ltir_reduced_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminltir_shockmaxminltir_responsecorecpi",
    "quadrant_panelthresholdlp_ltir_reduced_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminltir_shockmaxminltir",
    "quadrant_panelthresholdlp_ltir_reduced_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminltir_shockmaxminltir_responsegdp",
    "quadrant_panelthresholdlp_ltir_reduced_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminltir_shockmaxminltir_responsecorecpi",
    "quadrant_panelthresholdlp_m2_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminm2_shockmaxminepu",
    "quadrant_panelthresholdlp_m2_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminm2_shockmaxminepu_responsegdp",
    "quadrant_panelthresholdlp_m2_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminm2_shockmaxminepu_responsecorecpi",
    "quadrant_panelthresholdlp_m2_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminm2_shockmaxminepu",
    "quadrant_panelthresholdlp_m2_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminm2_shockmaxminepu_responsegdp",
    "quadrant_panelthresholdlp_m2_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminm2_shockmaxminepu_responsecorecpi",
    "quadrant_panelthresholdlp_m2_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminm2_shockmaxminm2",
    "quadrant_panelthresholdlp_m2_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminm2_shockmaxminm2_responsegdp",
    "quadrant_panelthresholdlp_m2_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminm2_shockmaxminm2_responsecorecpi",
    "quadrant_panelthresholdlp_m2_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminm2_shockmaxminm2",
    "quadrant_panelthresholdlp_m2_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminm2_shockmaxminm2_responsegdp",
    "quadrant_panelthresholdlp_m2_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminm2_shockmaxminm2_responsecorecpi",
    "quadrant_panelthresholdlp_m2_reduced_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminm2_shockmaxminepu",
    "quadrant_panelthresholdlp_m2_reduced_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminm2_shockmaxminepu_responsegdp",
    "quadrant_panelthresholdlp_m2_reduced_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminm2_shockmaxminepu_responsecorecpi",
    "quadrant_panelthresholdlp_m2_reduced_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminm2_shockmaxminepu",
    "quadrant_panelthresholdlp_m2_reduced_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminm2_shockmaxminepu_responsegdp",
    "quadrant_panelthresholdlp_m2_reduced_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminm2_shockmaxminepu_responsecorecpi",
    "quadrant_panelthresholdlp_m2_reduced_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminm2_shockmaxminm2",
    "quadrant_panelthresholdlp_m2_reduced_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminm2_shockmaxminm2_responsegdp",
    "quadrant_panelthresholdlp_m2_reduced_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminepu_maxminm2_shockmaxminm2_responsecorecpi",
    "quadrant_panelthresholdlp_m2_reduced_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminm2_shockmaxminm2",
    "quadrant_panelthresholdlp_m2_reduced_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminm2_shockmaxminm2_responsegdp",
    "quadrant_panelthresholdlp_m2_reduced_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminepu_maxminm2_shockmaxminm2_responsecorecpi",
    "quadrant_thresholdlp_us_jln_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminus_jln_maxminstir_shockmaxminus_jln",
    "quadrant_thresholdlp_us_jln_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminus_jln_maxminstir_shockmaxminus_jln_responsegdp",
    "quadrant_thresholdlp_us_jln_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminus_jln_maxminstir_shockmaxminus_jln_responsecorecpi",
    "quadrant_thresholdlp_us_jln_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminus_jln_maxminstir_shockmaxminus_jln",
    "quadrant_thresholdlp_us_jln_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminus_jln_maxminstir_shockmaxminus_jln_responsegdp",
    "quadrant_thresholdlp_us_jln_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminus_jln_maxminstir_shockmaxminus_jln_responsecorecpi",
    "quadrant_thresholdlp_us_jln_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminus_jln_maxminstir_shockmaxminstir",
    "quadrant_thresholdlp_us_jln_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminus_jln_maxminstir_shockmaxminstir_responsegdp",
    "quadrant_thresholdlp_us_jln_irf_hhdebt_ngdp0_govdebt_ngdp0modwith_maxminus_jln_maxminstir_shockmaxminstir_responsecorecpi",
    "quadrant_thresholdlp_us_jln_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminus_jln_maxminstir_shockmaxminstir",
    "quadrant_thresholdlp_us_jln_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminus_jln_maxminstir_shockmaxminstir_responsegdp",
    "quadrant_thresholdlp_us_jln_irf_hhdebt_ngdp1_govdebt_ngdp1modwith_maxminus_jln_maxminstir_shockmaxminstir_responsecorecpi",
    "quadrant_panelthresholdlp_irf_modwith_maxminepu_maxminstir_shockmaxminepu_responsegdp",
    "quadrant_panelthresholdlp_irf_modwith_maxminepu_maxminstir_shockmaxminepu_responsecorecpi",
    "quadrant_panelthresholdlp_irf_modwith_maxminepu_maxminstir_shockmaxminstir_responsegdp",
    "quadrant_panelthresholdlp_irf_modwith_maxminepu_maxminstir_shockmaxminstir_responsecorecpi",
    "quadrant_panelthresholdlp_reduced_irf_modwith_maxminepu_maxminstir_shockmaxminepu_responsegdp",
    "quadrant_panelthresholdlp_reduced_irf_modwith_maxminepu_maxminstir_shockmaxminepu_responsecorecpi",
    "quadrant_panelthresholdlp_reduced_irf_modwith_maxminepu_maxminstir_shockmaxminstir_responsegdp",
    "quadrant_panelthresholdlp_reduced_irf_modwith_maxminepu_maxminstir_shockmaxminstir_responsecorecpi",
    "quadrant_panelthresholdlp_ltir_irf_modwith_maxminepu_maxminltir_shockmaxminepu_responsegdp",
    "quadrant_panelthresholdlp_ltir_irf_modwith_maxminepu_maxminltir_shockmaxminepu_responsecorecpi",
    "quadrant_panelthresholdlp_ltir_irf_modwith_maxminepu_maxminltir_shockmaxminltir_responsegdp",
    "quadrant_panelthresholdlp_ltir_irf_modwith_maxminepu_maxminltir_shockmaxminltir_responsecorecpi",
    "quadrant_panelthresholdlp_ltir_reduced_irf_modwith_maxminepu_maxminltir_shockmaxminepu_responsegdp",
    "quadrant_panelthresholdlp_ltir_reduced_irf_modwith_maxminepu_maxminltir_shockmaxminepu_responsecorecpi",
    "quadrant_panelthresholdlp_ltir_reduced_irf_modwith_maxminepu_maxminltir_shockmaxminltir_responsegdp",
    "quadrant_panelthresholdlp_ltir_reduced_irf_modwith_maxminepu_maxminltir_shockmaxminltir_responsecorecpi",
    "quadrant_panelthresholdlp_m2_irf_modwith_maxminepu_maxminm2_shockmaxminepu_responsegdp",
    "quadrant_panelthresholdlp_m2_irf_modwith_maxminepu_maxminm2_shockmaxminepu_responsecorecpi",
    "quadrant_panelthresholdlp_m2_irf_modwith_maxminepu_maxminm2_shockmaxminm2_responsegdp",
    "quadrant_panelthresholdlp_m2_irf_modwith_maxminepu_maxminm2_shockmaxminm2_responsecorecpi",
    "quadrant_panelthresholdlp_m2_reduced_irf_modwith_maxminepu_maxminm2_shockmaxminepu_responsegdp",
    "quadrant_panelthresholdlp_m2_reduced_irf_modwith_maxminepu_maxminm2_shockmaxminepu_responsecorecpi",
    "quadrant_panelthresholdlp_m2_reduced_irf_modwith_maxminepu_maxminm2_shockmaxminm2_responsegdp",
    "quadrant_panelthresholdlp_m2_reduced_irf_modwith_maxminepu_maxminm2_shockmaxminm2_responsecorecpi",
    "quadrant_thresholdlp_us_jln_irf_modwith_maxminus_jln_maxminstir_shockmaxminus_jln_responsegdp",
    "quadrant_thresholdlp_us_jln_irf_modwith_maxminus_jln_maxminstir_shockmaxminus_jln_responsecorecpi",
    "quadrant_thresholdlp_us_jln_irf_modwith_maxminus_jln_maxminstir_shockmaxminstir_responsegdp",
    "quadrant_thresholdlp_us_jln_irf_modwith_maxminus_jln_maxminstir_shockmaxminstir_responsecorecpi",
    # "panelthresholdlp_irf_modwith_maxminepu_maxminstir_shockmaxminepu",
    # "panelthresholdlp_irf_modwith_maxminepu_maxminstir_shockmaxminstir",
    # "panelthresholdlp_irf_on_modwith_maxminepu_maxminstir_shockmaxminepu",
    # "panelthresholdlp_irf_on_modwith_maxminepu_maxminstir_shockmaxminstir",
    # "panelthresholdlp_irf_off_modwith_maxminepu_maxminstir_shockmaxminepu",
    # "panelthresholdlp_irf_off_modwith_maxminepu_maxminstir_shockmaxminstir",
    # "panelthresholdlp_ltir_irf_modwith_maxminepu_maxminltir_shockmaxminepu",
    # "panelthresholdlp_ltir_irf_modwith_maxminepu_maxminltir_shockmaxminltir",
    # "panelthresholdlp_reduced_irf_modwith_maxminepu_maxminstir_shockmaxminepu",
    # "panelthresholdlp_reduced_irf_modwith_maxminepu_maxminstir_shockmaxminstir",
    # "panelthresholdlp_ltir_reduced_irf_modwith_maxminepu_maxminltir_shockmaxminepu",
    # "panelthresholdlp_ltir_reduced_irf_modwith_maxminepu_maxminltir_shockmaxminltir",
    # "panelthresholdlp_m2_irf_modwith_maxminepu_maxminm2_shockmaxminepu",
    # "panelthresholdlp_m2_irf_modwith_maxminepu_maxminm2_shockmaxminm2",
    # "panelthresholdlp_ber_irf_modwith_maxminepu_maxminstir_shockmaxminepu",
    # "panelthresholdlp_ber_irf_modwith_maxminepu_maxminstir_shockmaxminstir",
    # "panellp_irf_modwith_maxminepu_maxminstir_shockmaxminepu",
    # "panellp_irf_modwith_maxminepu_maxminstir_shockmaxminstir",
    # "thresholdlp_irf_us_jln_modwith_maxminus_jln_maxminstir_shockmaxminus_jln",
    # "thresholdlp_irf_us_jln_modwith_maxminus_jln_maxminstir_shockmaxminstir",
]
selected_file_names = [i + ".png" for i in selected_file_names]
copy_files(
    input_path=path_output,
    input_file_names=selected_file_names,
    output_path=path_for_paper,
)

# %%
# X --- Notify
# End
print("\n----- Ran in " + "{:.0f}".format(time.time() - time_start) + " seconds -----")

# %%
